### ISSUE TITLE
怎么在上传二进制流时  添加自定义参数

### ISSUE THREAD

**Issue by leekangtaqi** [node-modules/qn#9]
怎么添加自定义参数和魔法变量

**Comment by fengmk2** [comment]
form表单里面的参数？还是header里面的？

**Comment by leekangtaqi** [comment]
我在微信网站中上传图片，得到个微信提供的id
通过这个id 在我的服务端发客户端请求 ，拿到二进制数据
然后再用您的api 保存到qn  返回的url 读不出数据
